name: Black Code Formatter
on: [workflow_dispatch, pull_request]
jobs:
  linter_name:
    name: Black Code Formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check files using the Black Code Formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "."
          fail_on_error: 'true'
      - name: Create Pull Request
        if: steps.action_black.outputs.is_formatted == 'true'
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.CPR }}
          title: "Format Python code with Black Code Formatter"
          commit-message: ":art: Format Python code with Black Code Formatter"
          body: |
            There appear to be some python formatting errors in ${{ github.sha }}. This pull request
            uses the [Black Code Formatter](https://github.com/psf/black) to fix these issues.
          base: ${{ github.head_ref }} # Creates pull request onto pull request or commit branch
          delete-branch: true
          branch: actions/black
