name: Draft PR for New Branches
on:
  workflow_dispatch:
  create:
    ref_type: branch    
    branches-ignore:
      - dev
      - newdev
jobs:
  new_branch_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - run: echo Branch ${GITHUB_REF##*/}
