name: My Python Linter (autoflake, isort, black)

on: [workflow_dispatch, pull_request]

jobs:
  python_linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #- name: Black Code Formatter
      #  uses: lgeiger/black-action@master
      #  with:
      #    args: ". --diff --color --check"
      - uses: sailingpalmtree/lint@latest
        with:
          github_token: ${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}
          # Change reviewdog reporter if you need [github-pr-check,github-check,github-pr-review].
          reporter: github-pr-review
          # Change reporter level if you need.
          # GitHub Status Check won't become failure with warning.
          level: warning
