name: Create new Branch and Release
on:
  workflow_dispatch:
  release:
    types: [released]
jobs:
  new_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Create Pull Request
        if: ${{ steps.action_create_branch.outputs.created }}
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          base: newdev
          branch: dev
          delete-branch: true
          title: Development PR
          labels: ignore-for-release
          draft: true
