name: Create new Branch and Release
on:
  workflow_dispatch:
  release:
    types: [released]
jobs:
  new_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Create New Dev branch
        run: git checkout -b dev
      - name: Empty Commit
        run: git commit --allow-empty -m "Empty commit"
      #- name: Initialize mandatory git config
      #  run: |
      #    git config user.name "GitHub Actions"
      #    git config user.email noreply@github.com
      #- name: Create Pull Request
      #  id: cpr
      #  uses: peter-evans/create-pull-request@v4
      #  with:
      #    base: newdev
      #    branch: dev
      #    delete-branch: false
      #    title: Development PR
      #    labels: ignore-for-release
      #    draft: true
