name: Create New Dev Branch and PR
on:
  workflow_dispatch:
  release:
    types: [released]
jobs:
  new_dev_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Create and Checkout New Dev branch
        run: | 
          git branch dev --set-upstream-to=${{ github.event.repository.default_branch }}
          git checkout dev
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: Empty Commit
        run: git commit --allow-empty -m "Empty commit"
      #- name: Create Pull Request
      #  id: cpr
      #  uses: peter-evans/create-pull-request@v4
      #  with:
      #    base: newdev
      #    branch: dev
      #    delete-branch: false
      #    title: Development PR
      #    labels: ignore-for-release
      #    draft: true
