name: Create new Branch and Release
on:
  workflow_dispatch:
  release:
    types: [released]
jobs:
  new_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional. Commit message for the created commit.
          # Defaults to "Apply automatic changes"
          commit_message: Automated Change

          # Optional. Local and remote branch name where commit is going to be pushed
          #  to. Defaults to the current branch.
          #  You might need to set `create_branch: true` if the branch does not exist.
          branch: dev

          # Optional. Options used by `git-commit`.
          # See https://git-scm.com/docs/git-commit#_options
          commit_options: '--allow-empty'

          # Optional. Disable dirty check and always try to create a commit and push
          skip_dirty_check: true
          
          # Optional. Create given branch name in local and remote repository.
          create_branch: true
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          base: newdev
          branch: dev
          delete-branch: true
          title: Development PR
          labels: ignore-for-release
          draft: true
