name: Create new Branch and Release
on:
  workflow_dispatch:
  release:
    types: [released]

uses: peterjgrainger/action-create-branch@v2.2.0
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
with:
  branch: 'dev'
  sha: '${{ github.event.pull_request.head.sha }}'
