name: Create new Branch and Release
on:
  workflow_dispatch:
  release:
    types: [released]
jobs:
  new_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3



    
      - name: Create new dev branch
        if: ${{ steps.cpr.outputs.pull-request-number }}
        id: create_branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'dev'


      # Make changes to pull request here

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
